version: '3'
services:
  app:
    env_file: .env
    restart: always
    image: 'jc21/nginx-proxy-manager:latest'
    environment:
      # These are the settings to access your db
      DB_MYSQL_HOST: $DB_MYSQL_HOST
      DB_MYSQL_PORT: $DB_MYSQL_PORT
      DB_MYSQL_USER: $DB_MYSQL_USER
      DB_MYSQL_PASSWORD: $DB_MYSQL_PASSWORD
      DB_MYSQL_NAME: $DB_MYSQL_NAME
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db

  db:
    env_file: .env
    restart: always
    image: jc21/mariadb-aria
    environment:
      MYSQL_ROOT_PASSWORD: $DB_MYSQL_PASSWORD
      MYSQL_DATABASE: $DB_MYSQL_NAME
      MYSQL_USER: $DB_MYSQL_USER
      MYSQL_PASSWORD: $DB_MYSQL_PASSWORD
    volumes:
      - ./data/mysql:/var/lib/mysql
  
  goaccess:
    image: 'xavierh/goaccess-for-nginxproxymanager:latest'
    container_name: goaccess
    restart: always
    ports:
        - '7880:7880'
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Mexico_City         
      - SKIP_ARCHIVED_LOGS=False #optional
      - DEBUG=False #optional
      - BASIC_AUTH=True #optional
      - BASIC_AUTH_USERNAME=user #optional
      - BASIC_AUTH_PASSWORD=password #optional   
      - EXCLUDE_IPS=127.0.0.1 #optional - comma delimited 
      - LOG_TYPE=NPM #optional - more information below
    volumes:
      - ./data/logs:/opt/log
    depends_on:
      - app